6CS012 - Artificial Intelligence and Machine Learning.
A Tutorial and Assessment on Python and NumPy for Deep

Learning.

Name: Utkarsha Aryal
ID:2407743 Grp:09
workshop 0


4.1 Exercise on Functions: Task 1 - Unit Converter
italicized text


In [1]:
def convert_units(value, unit_choice):
    """
    Performs conversion between different units of measurement.

    Parameters:
    value (float): The numerical value to be converted.
    unit_choice (str): The specific conversion type (e.g., 'm_to_ft').

    Returns:
    float: The converted value.
    """
    conversions = {
        '1': value * 3.28084,  # meters to feet
        '2': value / 3.28084,  # feet to meters
        '3': value * 2.20462,  # kg to lbs
        '4': value / 2.20462,  # lbs to kg
        '5': value * 0.264172, # liters to gallons
        '6': value / 0.264172  # gallons to liters
    }
    return conversions.get(unit_choice)

def main_converter():
    print("--- Unit Converter ---")
    print("1. Meters to Feet\n2. Feet to Meters")
    print("3. Kilograms to Pounds\n4. Pounds to Kilograms")
    print("5. Liters to Gallons\n6. Gallons to Liters")

    try:
        choice = input("Select conversion type (1-6): ")
        if choice not in ['1', '2', '3', '4', '5', '6']:
            raise ValueError("Unsupported conversion type.")

        val = float(input("Enter the value to convert: "))
        result = convert_units(val, choice)
        print(f"Result: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}. Please enter a valid number.")

# Run the task

main_converter()


--- Unit Converter ---
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Select conversion type (1-6): 1
Enter the value to convert: 50
Result: 164.04


4.1 Exercise on Functions: Task 2 - List Operations


In [3]:
def calculate_stats(numbers, operation):
    """
    Performs mathematical operations on a list of numbers.

    Parameters:
    numbers (list): List of floats.
    operation (str): 'sum', 'average', 'max', or 'min'.

    Returns:
    float: Result of the operation.
    """
    if not numbers:
        raise ValueError("The list is empty.")

    if operation == 'sum':
        return sum(numbers)
    elif operation == 'average':
        return sum(numbers) / len(numbers)
    elif operation == 'max':
        return max(numbers)
    elif operation == 'min':
        return min(numbers)
    else:
        raise ValueError("Invalid operation.")

def main_list_math():
    try:
        user_input = input("Enter numbers separated by spaces: ")
        num_list = [float(x) for x in user_input.split()]

        print("\nChoose Operation: sum, average, max, min")
        op = input("Enter operation: ").lower()

        result = calculate_stats(num_list, op)
        print(f"The {op} is: {result}")

    except ValueError as e:
        print(f"Input Error: {e}")

# Run the task
main_list_math()

Enter numbers separated by spaces: 9

Choose Operation: sum, average, max, min
Enter operation: max
The max is: 9.0


4.2 Exercise on List Manipulation


In [4]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]

# 2. Slice a Sublist (Inclusive end)
def get_sublist(lst, start, end):
    return lst[start:end+1]

# 3. Reverse a List
def reverse_list(lst):
    return lst[::-1]

# 4. Remove First and Last
def remove_first_last(lst):
    return lst[1:-1]

# 5. Get First n Elements
def get_first_n(lst, n):
    return lst[:n]

# 6. Extract n Elements from the End
def get_last_n(lst, n):
    return lst[-n:]

# 7. Extract in Reverse Order (Skipping one)
def reverse_skip(lst):
    # Starts from second-to-last, moves backward skipping one
    return lst[-2::-2]

# --- TESTING THE FUNCTIONS ---
sample = [1, 2, 3, 4, 5, 6]
print("Original:", sample)
print("1. Every Other:", extract_every_other(sample))
print("2. Sublist (2 to 4):", get_sublist(sample, 2, 4))
print("7. Reverse Skip:", reverse_skip(sample)) # Should be [5, 3, 1]


Original: [1, 2, 3, 4, 5, 6]
1. Every Other: [1, 3, 5]
2. Sublist (2 to 4): [3, 4, 5]
7. Reverse Skip: [5, 3, 1]


4.3 Exercise on Nested Lists


In [5]:
# 1. Flatten a Nested List (One level)
def flatten(lst):
    return [item for sublist in lst for item in sublist]

# 2. Access Nested Element using index list [i, j]
def access_nested_element(lst, indices):
    return lst[indices[0]][indices[1]]

# 3. Sum of All Elements (Recursive for any depth)
def sum_nested(lst):
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total

# 4. Remove Specific Element from Nested List
def remove_element(lst, elem):
    return [[x for x in sub if x != elem] for sub in lst]

# 5. Find Maximum (Recursive)
def find_max(lst):
    flat_list = []
    def get_flat(l):
        for i in l:
            if isinstance(i, list): get_flat(i)
            else: flat_list.append(i)
    get_flat(lst)
    return max(flat_list)

# 7. Deep Flatten (Multi-level)
def deep_flatten(lst):
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)
    return result

# 8. Nested List Average
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

# --- TESTING ---
nested_sample = [[1, 2], [3, [4, 5]], 6]
print("Deep Flatten:", deep_flatten(nested_sample))
print("Sum of Nested:", sum_nested(nested_sample))
print("Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

Deep Flatten: [1, 2, 3, 4, 5, 6]
Sum of Nested: 21
Average: 3.5


10.1 & 10.2 Basic NumPy & Performance Experiment


In [6]:
import numpy as np
import time

# --- 10.1 Problem 1 & 2: Creation & Manipulation ---
print("--- NumPy Creation ---")
empty_arr = np.empty((2,2))
ones_arr = np.ones((4,2))
range_arr = np.arange(10, 50)
matrix_3x3 = np.arange(9).reshape(3,3)
identity = np.eye(3)

# Checkerboard 8x8
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard:\n", checkerboard)

# --- 10.1 Problem 4: Matrix Operations & Proofs ---
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
identity_proof = np.dot(A, A_inv)
print("\nA * A_inv (Should be Identity):\n", np.round(identity_proof))

# 2. Solve Linear Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
coeffs = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
results = np.array([-1, -3, 9])
solution = np.linalg.solve(coeffs, results)
print("\nSolution to Linear Equations (x, y, z):", solution)

# --- 10.2 Performance Experiment ---
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.array(list1)
arr2 = np.array(list2)

# Python List Addition
start = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
list_time = time.time() - start

# NumPy Array Addition
start = time.time()
arr_sum = arr1 + arr2
numpy_time = time.time() - start

print(f"\n--- Performance Results ---")
print(f"Python List Time: {list_time:.5f}s")
print(f"NumPy Array Time: {numpy_time:.5f}s")
print(f"NumPy is {list_time / numpy_time:.2f}x faster!")

--- NumPy Creation ---
8x8 Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

A * A_inv (Should be Identity):
 [[1. 0.]
 [0. 1.]]

Solution to Linear Equations (x, y, z): [ 2.  1. -2.]

--- Performance Results ---
Python List Time: 0.06723s
NumPy Array Time: 0.00383s
NumPy is 17.57x faster!
